/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import java.util.Random;

/**
 *
 * @author Ignacio
 */
public class VentanaJugada extends javax.swing.JFrame {

    //Declaramos la Clase Opciones
    Opciones opciones = new Opciones();

    //Clase Mano
    Jugada partidaJugadores;
    
    //Estado del Juego
    boolean iniciar = false;
    
    public VentanaJugada() {
        initComponents();
        
        //Centramos la ventana
        setLocationRelativeTo(null);
        
        //Establecemos las Opciones por Defecto de la Ventana
        setOpcionesVentana();
        
        //Reiniciamos la Partida
        reinicarPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPJugador = new javax.swing.JPanel();
        jBPiedraJugador = new javax.swing.JButton();
        jBPapelJugador = new javax.swing.JButton();
        jBTijeraJugador = new javax.swing.JButton();
        jTFWinJugador = new javax.swing.JTextField();
        jLMensajeJugador = new javax.swing.JLabel();
        jPOponente = new javax.swing.JPanel();
        jTFWinOponente = new javax.swing.JTextField();
        jLPiedraOponente = new javax.swing.JLabel();
        jLPapelOponente = new javax.swing.JLabel();
        jLTijeraOponente = new javax.swing.JLabel();
        jLMensajeOponente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFRestantes = new javax.swing.JTextField();
        jBIniciar = new javax.swing.JButton();
        jBOpciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piedra Papel Tijera");

        jPJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador"));

        jBPiedraJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Piedra.png"))); // NOI18N
        jBPiedraJugador.setToolTipText("Piedra");
        jBPiedraJugador.setEnabled(false);
        jBPiedraJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraJugadorActionPerformed(evt);
            }
        });

        jBPapelJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Papel.png"))); // NOI18N
        jBPapelJugador.setToolTipText("Papel");
        jBPapelJugador.setEnabled(false);
        jBPapelJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPapelJugadorActionPerformed(evt);
            }
        });

        jBTijeraJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tijera.png"))); // NOI18N
        jBTijeraJugador.setToolTipText("Tijera");
        jBTijeraJugador.setEnabled(false);
        jBTijeraJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTijeraJugadorActionPerformed(evt);
            }
        });

        jTFWinJugador.setEditable(false);
        jTFWinJugador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTFWinJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFWinJugador.setText("0");

        jLMensajeJugador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLMensajeJugador.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPJugadorLayout = new javax.swing.GroupLayout(jPJugador);
        jPJugador.setLayout(jPJugadorLayout);
        jPJugadorLayout.setHorizontalGroup(
            jPJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPJugadorLayout.createSequentialGroup()
                        .addComponent(jBPiedraJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPapelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTijeraJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPJugadorLayout.createSequentialGroup()
                        .addComponent(jLMensajeJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFWinJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPJugadorLayout.setVerticalGroup(
            jPJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBTijeraJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPapelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPiedraJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFWinJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMensajeJugador)))
        );

        jPOponente.setBorder(javax.swing.BorderFactory.createTitledBorder("Oponente"));

        jTFWinOponente.setEditable(false);
        jTFWinOponente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTFWinOponente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFWinOponente.setText("0");

        jLPiedraOponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPiedraOponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Piedra.png"))); // NOI18N
        jLPiedraOponente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLPiedraOponente.setEnabled(false);
        jLPiedraOponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLPapelOponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPapelOponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Papel.png"))); // NOI18N
        jLPapelOponente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLPapelOponente.setEnabled(false);
        jLPapelOponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLTijeraOponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTijeraOponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tijera.png"))); // NOI18N
        jLTijeraOponente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLTijeraOponente.setEnabled(false);
        jLTijeraOponente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLMensajeOponente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLMensajeOponente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPOponenteLayout = new javax.swing.GroupLayout(jPOponente);
        jPOponente.setLayout(jPOponenteLayout);
        jPOponenteLayout.setHorizontalGroup(
            jPOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOponenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOponenteLayout.createSequentialGroup()
                        .addComponent(jTFWinOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLMensajeOponente))
                    .addGroup(jPOponenteLayout.createSequentialGroup()
                        .addComponent(jLPiedraOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLPapelOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLTijeraOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPOponenteLayout.setVerticalGroup(
            jPOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOponenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPiedraOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPapelOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTijeraOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFWinOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMensajeOponente)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Restantes:");

        jTFRestantes.setEditable(false);
        jTFRestantes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTFRestantes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFRestantes.setText("0");
        jTFRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRestantesActionPerformed(evt);
            }
        });

        jBIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nueva_Partida.png"))); // NOI18N
        jBIniciar.setToolTipText("Iniciar Partida");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });

        jBOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Option.png"))); // NOI18N
        jBOpciones.setToolTipText("Configuración del Juego");
        jBOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPOponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed
        //Si la Partida ya esta Iniciada -> Reiniciamos 
        if (iniciar)
            reinicarPartida();
        //Si la Partida esta Parada -> Iniciamos
        else
            iniciarPartida();            
    }//GEN-LAST:event_jBIniciarActionPerformed
    private void reinicarPartida(){
        jTFWinJugador.setText("0");
        jTFWinOponente.setText("0");
        jLMensajeJugador.setText("");
        jLMensajeOponente.setText("");
        jTFRestantes.setText(String.valueOf(opciones.getNumPartidas()));
        jBIniciar.setToolTipText("Iniciar Partida");
        desactivaBotones();
        iniciar = false;
        jBIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagenes/Nueva_Partida.png")));
    }
    private void desactivaBotones(){
        jBPiedraJugador.setEnabled(false);
        jLPiedraOponente.setEnabled(false);
        jBPapelJugador.setEnabled(false);
        jLPapelOponente.setEnabled(false);
        jBTijeraJugador.setEnabled(false);
        jLTijeraOponente.setEnabled(false);
    }
    
    
    private void iniciarPartida(){
        jBIniciar.setToolTipText("Reiniciar Partida");
        jBPiedraJugador.setEnabled(true);
        jBPapelJugador.setEnabled(true);
        jBTijeraJugador.setEnabled(true);
        iniciar = true;        
        jBIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagenes/Restart.png")));
        
        //Creamos 1 objeto de tipo Jugada
        partidaJugadores = new Jugada(opciones.getNombre(), opciones.NOM_OPONENTE, opciones.getNumPartidas());
    }
    
    //*******
    private void setJugadaOrdenador(){
        Random generadorNum = new Random();
        int jugadaOrdenador = generadorNum.nextInt(3) + 1;

        //Establecemo la Nueva Mano del Ordenador
        partidaJugadores.setJugadaB(jugadaOrdenador);
        
        //Marcamos el Boton del Ordenador
        setBotonOrdenador(jugadaOrdenador);
    }
    /****/
    private void setBotonOrdenador(int jugadaOrdenador){
        //Desactivamos todos por defecto
        jLPiedraOponente.setEnabled(false);
        jLPapelOponente.setEnabled(false);
        jLTijeraOponente.setEnabled(false);
        
        switch(jugadaOrdenador){
            case Jugada.PIEDRA:
                jLPiedraOponente.setEnabled(true);
                break;
            case Jugada.PAPEL:
                jLPapelOponente.setEnabled(true);
                break;
            case Jugada.TIJERA:
                jLTijeraOponente.setEnabled(true);
                break;
        }
    }
    
    private void jBOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOpcionesActionPerformed

        //Declaramos objeto del tipo VentanaOpciones
        VentanaOpciones ventanaOpciones = new VentanaOpciones(this, true, opciones);

        //Mostrar la ventana de diálogo
        ventanaOpciones.setVisible(true);
        
        //Si se ha pulsado Aceptar
        if (ventanaOpciones.isBtnAceptar()){
            
            //Copiamos las Nuevas Opciones
            opciones = ventanaOpciones.getOpciones();
            
            //Establecemos las Opciones por Defecto de la Ventana
            setOpcionesVentana();
            
            //Reiniciamos la Partida
            reinicarPartida();
        }
    }//GEN-LAST:event_jBOpcionesActionPerformed
    
    private void setOpcionesVentana(){
        jTFWinJugador.setBackground(opciones.getColorJugador());
        jPJugador.setBackground(opciones.getColorJugador());
        jTFWinOponente.setBackground(opciones.getColorPC());
        jPOponente.setBackground(opciones.getColorPC());
        jPJugador.setBorder(javax.swing.BorderFactory.createTitledBorder(opciones.getNombre()));
    }
    
    private void jTFRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRestantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRestantesActionPerformed

    private void jBPapelJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPapelJugadorActionPerformed
        setJugada(Jugada.PAPEL);
        //partidaJugadores.setJugadaA(Jugada.PAPEL);
    }//GEN-LAST:event_jBPapelJugadorActionPerformed

    private void jBPiedraJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPiedraJugadorActionPerformed
        setJugada(Jugada.PIEDRA);
        //partidaJugadores.setJugadaA(Jugada.PIEDRA);
    }//GEN-LAST:event_jBPiedraJugadorActionPerformed

    private void jBTijeraJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTijeraJugadorActionPerformed
        setJugada(Jugada.TIJERA);
        //partidaJugadores.setJugadaA(Jugada.TIJERA);
    }//GEN-LAST:event_jBTijeraJugadorActionPerformed

    //*******
    private void setJugada(int manoJugador){
        
        //Establecemos la Jugada del Jugador A
        partidaJugadores.setJugadaA(manoJugador);

        //Establecemos la Jugada del Jugador B ******
        setJugadaOrdenador();
        
        //Comprueba quien ha ganado
        int ganador = partidaJugadores.getGanadorJugada();
        
        //Refrescamos el Marcador
        jTFWinJugador.setText(String.valueOf(partidaJugadores.getGanadasA()));
        jTFWinOponente.setText(String.valueOf(partidaJugadores.getGanadasB()));
        
        //Indicamos quien ha ganado esta mano
        switch(ganador){
            case Jugada.GANA_A:
                System.out.println("Ha ganado A");
                break;
            case Jugada.EMPATE:
                System.out.println("Empate");
                break;
            case Jugada.GANA_B:
                System.out.println("Ha ganado B");
                break;
        }
        //Restamos el Numero de Partidas Restantes
        partidaJugadores.restaPartida(jTFRestantes);
        
        //Comprueba si es el Final de la Partida
        if (partidaJugadores.isFinalPartida()){
            //Desactivamos los Botones
            desactivaBotones();
            
            //Comprobamos quien ha ganado la partida
            int ganadorPartida = partidaJugadores.getGanandoPartida();

            //Si la Partida la ha jugado el Jugador A
            if (ganadorPartida == Jugada.GANA_A){
                jLMensajeJugador.setText("Ha ganado");
                jLMensajeOponente.setText("Ha perdido");
            }
            //Si la Partida la ha jugado el Jugador B
            else if (ganadorPartida == Jugada.GANA_B){
                jLMensajeOponente.setText("Ha ganado");
                jLMensajeJugador.setText("Ha perdido");
            }
            //Si hay Empate
            else{
                jLMensajeJugador.setText("Empate");
                jLMensajeOponente.setText("Empate");                
            }
        }
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJugada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJugada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJugada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJugada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJugada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jBOpciones;
    private javax.swing.JButton jBPapelJugador;
    private javax.swing.JButton jBPiedraJugador;
    private javax.swing.JButton jBTijeraJugador;
    private javax.swing.JLabel jLMensajeJugador;
    private javax.swing.JLabel jLMensajeOponente;
    private javax.swing.JLabel jLPapelOponente;
    private javax.swing.JLabel jLPiedraOponente;
    private javax.swing.JLabel jLTijeraOponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPJugador;
    private javax.swing.JPanel jPOponente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFRestantes;
    private javax.swing.JTextField jTFWinJugador;
    private javax.swing.JTextField jTFWinOponente;
    // End of variables declaration//GEN-END:variables
}
